/*
 * Simple Inventory API
 *
 * Sample Books API
 *
 * API version: 1.0.0
 * Contact: damasiormoura@gmail.com.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"encoding/json"
	"net/http"
)

func SearchBook(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	books := AllBooks()
	b, err := json.Marshal(books)
	if err != nil {
		panic(err)
	}
	w.WriteHeader(http.StatusOK)
	w.Write(b)
}
